info:
  name: ${project.name}
  version: ${project.version}
  description: ${project.description}

spring:
  application:
    name: zuul-eureka

logging:
  level:
    root: INFO

server:
  PORT: 8761

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 20000
    response-cache-update-interval-ms: 10000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}