# Application properties for Gateway server

server:
  port: 8000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

hystrix:
  command:
    microservice:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000

microservice:
  ribbon:
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true

ribbon:
  eureka:
    enabled: true

zuul:
  ignored-services: '*'
  retryable: true
  host:
    max-total-connections: 100
    max-per-route-connections: 100
  routes:
    microservice:
      path: /api/**
      sensitive-headers: null
      service-id: microservice
      strip-prefix: false
      ssl-hostname-validation-enabled: false

spring:
  boot:
    admin:
      client:
        url: 'http://localhost:8090'

management:
  endpoints:
    web:
      exposure:
        include: '*'

